### ISSUE TITLE
Version 0.0.9 fails to load (says connection got closed and server will not be restarted)

### ISSUE THREAD

**Issue by thomazmoura** [iamcco/coc-angular#3]
I'm running Raspbian on a Raspberry PI 3B and using it to develop on NeoVim with COC.

Since version 0.0.9 coc-angular doesn't load anymore. It outputs the following error everytime I open an angular file:

```
[coc.nvim] Error output from angularls: Connection to the server got closed. Server will not be restarted.
```

Rolling back to previous version (:CocInstall coc-angular@0.0.8) fixes it though (until it updates back automatically).

**Comment by iamcco** [comment]
upload the angularls output channel to see what happend.

`CocList output` and select angularls

**Comment by thomazmoura** [comment]
Here is the output:

```
internal/modules/cjs/loader.js:584
      throw err;
      ^

  Error: Cannot find module '@angular/compiler-cli/src/language_services'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
      at Function.Module._load (internal/modules/cjs/loader.js:508:25)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at /home/thomaz/.config/coc/extensions/node_modules/@angular/language-service/src/completions.js:21:31
      at /home/thomaz/.config/coc/extensions/node_modules/@angular/language-service/src/completions.js:10:17
      at Object.<anonymous> (/home/thomaz/.config/coc/extensions/node_modules/@angular/language-service/src/completions.js:16:3)
      at Module._compile (internal/modules/cjs/loader.js:701:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
      at Module.load (internal/modules/cjs/loader.js:600:32)
  [Info  - 2:42:05 AM] Connection to server got closed. Server will restart.
  internal/modules/cjs/loader.js:584
      throw err;
      ^
```

I've just tested the same project on my Desktop (running Ubuntu-based KDE Neon) and it works fine on 0.0.0.9. On the Raspbian, though, the result is still the same (works on 0.0.8 and breaks on 0.0.0.9)

**Comment by iamcco** [comment]
Update and have a try

**Comment by thomazmoura** [comment]
It works fine on the new version (0.0.11).
Thank you very much.
